# Telegraf Configuration
[agent]
  interval = "10s" # Fetch data every 10 seconds
  debug = true

#INPUT: fetching data from delta api
[[inputs.http]]
  urls = []
  method = "GET"
  timeout = "5s"
  headers = { Content-Type = "application/json" }
  data_format = "json"
  
  # Authentication
  username = "rasmus.luha"
  password = "Placeholder"

  # Response format
  #data_format = "json"

  # Specify JSON field
  json_query = "placeholder"  
  json_string_fields = []

  name_override = "Placeholder"  #"weather_metrics"


# OUTPUT: Write data to InfluxDB
[[outputs.influxdb]]
  urls = ["http://influxdb:8086"]
  database = "placeholder "#"telegraf_deltaEnergy"
  username = "TODO"
  password = "TODO"

